### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by dmzebrov** [ulixee/secret-agent#145]
Updated Secret Agent to 1.3.0-alpha.0 and now getting this error. MacOS 11.1. The simplest example code.

`TypeError: Cannot read property 'split' of undefined
    at extractOsVersion (/Users/dmz/.nvm/versions/node/v14.15.1/lib/node_modules/secret-agent/emulate-browsers/base/lib/getLocalOperatingSystemMeta.ts:27:21)
    at Object.getLocalOperatingSystemMeta [as default] (/Users/dmz/.nvm/versions/node/v14.15.1/lib/node_modules/secret-agent/emulate-browsers/base/lib/getLocalOperatingSystemMeta.ts:10:19)
    at Object.<anonymous> (/Users/dmz/.nvm/versions/node/v14.15.1/lib/node_modules/secret-agent/emulate-browsers/base/lib/DomDiffLoader.ts:5:48)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/dmz/.nvm/versions/node/v14.15.1/lib/node_modules/secret-agent/emulate-browsers/base/index.ts:8:1)`

**Comment by blakebyrnes** [comment]
@dmzebrov Shoot. I forgot to test on Big Sur. We've seen a number of issues there. I think this is one of them that has a fix in the emulators PR that's still in progress. Will get it pulled in and see if we can push out another release today.
