### ISSUE TITLE
Unable to run on macOS 

### ISSUE THREAD

**Issue by felyxjet** [ulixee/secret-agent#166]
```
$ mkdir secret-agent-test
$ cd secret-agent-test
$ npm i --save secret-agent

added 143 packages, and audited 144 packages in 1m

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ cat <<EOF > test.js
const agent = require('secret-agent');

(async () => {
  await agent.goto('https://example.org');
  const title = await agent.document.title;
  const intro = await agent.document.querySelector('p').textContent;
  await agent.close();
})();
EOF

$ node test.js

(node:9095) UnhandledPromiseRejectionWarning: Error: Emulator could not find a version match for mac-os 11-2
    at extractFilename (/Users/felyxjet/srv/secret-agent-test/emulate-browsers/base/lib/DomDiffLoader.ts:49:11)
    at DomDiffLoader.get (/Users/felyxjet/srv/secret-agent-test/emulate-browsers/base/lib/DomDiffLoader.ts:18:24)
    at new Chrome83 (/Users/felyxjet/srv/secret-agent-test/emulate-browsers/chrome-83/index.ts:80:39)
    at new Session (/Users/felyxjet/srv/secret-agent-test/node_modules/core/lib/Session.ts:80:28)
    at Function.createSessionNow (/Users/felyxjet/srv/secret-agent-test/node_modules/core/lib/GlobalPool.ts:136:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ConnectionToClient.createSession (/Users/felyxjet/srv/secret-agent-test/node_modules/core/server/ConnectionToClient.ts:168:21)
    at ConnectionToClient.handleRequest (/Users/felyxjet/srv/secret-agent-test/node_modules/core/server/ConnectionToClient.ts:51:18)
------CONNECTION----------------------------------
    at Object.createPromise (/Users/felyxjet/srv/secret-agent-test/node_modules/commons/utils.ts:39:10)
    at RemoteConnectionToCore.createPendingResult (/Users/felyxjet/srv/secret-agent-test/node_modules/client/connections/ConnectionToCore.ts:206:31)
    at RemoteConnectionToCore.internalSendRequestAndWait (/Users/felyxjet/srv/secret-agent-test/node_modules/client/connections/ConnectionToCore.ts:159:34)
    at RemoteConnectionToCore.sendRequest (/Users/felyxjet/srv/secret-agent-test/node_modules/client/connections/ConnectionToCore.ts:108:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at CoreCommandQueue.processQueue (/Users/felyxjet/srv/secret-agent-test/node_modules/client/lib/CoreCommandQueue.ts:64:28)
------CORE COMMANDS-------------------------------
    at CoreCommandQueue.run (/Users/felyxjet/srv/secret-agent-test/node_modules/client/lib/CoreCommandQueue.ts:43:14)
    at RemoteConnectionToCore.createSession (/Users/felyxjet/srv/secret-agent-test/node_modules/client/connections/ConnectionToCore.ts:138:49)
    at SessionConnection.connectSession (/Users/felyxjet/srv/secret-agent-test/node_modules/client/lib/Agent.ts:382:36)
    at SessionConnection.get activeTab [as activeTab] (/Users/felyxjet/srv/secret-agent-test/node_modules/client/lib/Agent.ts:316:10)
    at Agent.get activeTab [as activeTab] (/Users/felyxjet/srv/secret-agent-test/node_modules/client/lib/Agent.ts:98:37)
    at Agent.goto (/Users/felyxjet/srv/secret-agent-test/node_modules/client/lib/Agent.ts:228:17)
    at /Users/felyxjet/srv/secret-agent-test/test.js:4:15
    at Object.<anonymous> (/Users/felyxjet/srv/secret-agent-test/test.js:8:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9095) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9095) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

node version: 14.15.4
macOS version: 11.2.1
`~/Library/Caches/` contains only `chromium-756035`

**Comment by calebjclark** [comment]
That shouldn't be happening. It looks like I introduced a bug in the new emulators. I'll investigate and push out a fix.
