### ISSUE TITLE
fetch request not working

### ISSUE THREAD

**Issue by soermejo** [ulixee/secret-agent#220]
```
2021-04-20T13:15:06.628Z ERROR [C:\Users\seby\Documents\snipesbot\node_modules\@secret-agent\core\index] UnhandledErrorOrRejection {
  clientError: "Error: SyntaxError: Unexpected token ';'",
  context: {},
  sessionId: null,
  sessionName: undefined
} SyntaxError: Unexpected token ';'
------REMOTE CORE---------------------------------
    at Object.<anonymous> (C:\Users\seby\Documents\snipesbot\node_modules\commons\TypeSerializer.ts:44:28)
    at JSON.parse (<anonymous>)
    at Function.parse (C:\Users\seby\Documents\snipesbot\node_modules\commons\TypeSerializer.ts:6:17)
    at WebSocket.<anonymous> (C:\Users\seby\Documents\snipesbot\node_modules\client\connections\RemoteConnectionToCore.ts:67:42)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\seby\Documents\snipesbot\node_modules\ws\lib\websocket.js:835:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Users\seby\Documents\snipesbot\node_modules\ws\lib\receiver.js:437:14)
    at Receiver.getData (C:\Users\seby\Documents\snipesbot\node_modules\ws\lib\receiver.js:367:17)
    at Receiver.startLoop (C:\Users\seby\Documents\snipesbot\node_modules\ws\lib\receiver.js:143:22)
------CONNECTION----------------------------------
    at Object.createPromise (C:\Users\seby\Documents\snipesbot\node_modules\commons\utils.ts:39:10)
    at RemoteConnectionToCore.createPendingResult (C:\Users\seby\Documents\snipesbot\node_modules\client\connections\ConnectionToCore.ts:315:31)
    at RemoteConnectionToCore.internalSendRequestAndWait (C:\Users\seby\Documents\snipesbot\node_modules\client\connections\ConnectionToCore.ts:242:43)
    at RemoteConnectionToCore.sendRequest (C:\Users\seby\Documents\snipesbot\node_modules\client\connections\ConnectionToCore.ts:149:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.cb (C:\Users\seby\Documents\snipesbot\node_modules\client\lib\CoreCommandQueue.ts:37:26)
    at Queue.next (C:\Users\seby\Documents\snipesbot\node_modules\commons\Queue.ts:71:19)
------CORE COMMANDS-------------------------------
    at Queue.run (C:\Users\seby\Documents\snipesbot\node_modules\commons\Queue.ts:28:19)
    at CoreCommandQueue.run (C:\Users\seby\Documents\snipesbot\node_modules\client\lib\CoreCommandQueue.ts:36:8)
    at CoreFrameEnvironment.fetch (C:\Users\seby\Documents\snipesbot\node_modules\client\lib\CoreFrameEnvironment.ts:52:36)
    at FrameEnvironment.fetch (C:\Users\seby\Documents\snipesbot\node_modules\client\lib\FrameEnvironment.ts:118:43)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Tab.fetch (C:\Users\seby\Documents\snipesbot\node_modules\client\lib\Tab.ts:121:12)
    at file:///C:/Users/seby/Documents/snipesbot/main.js:10:8

--------------------------------------------------
------default-session-----------------------------
------6c74d2b0-a1da-11eb-b508-67d2194df520--------
-------------------------------------------------- {
  isDisconnecting: false
}
```

**CODE:**
```
import agent from 'secret-agent'

await agent.configure({
  blockedResourceTypes: ["BlockImages"],
});


(async () => {
	res = await agent.fetch("https://127.0.0.1:8080/px")
	console.log(res)
	await agent.close();
})();
```

**Package.json:**
```
{
  "name": "snipesbot",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "type": "module",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "puppeteer": "^8.0.0",
    "puppeteer-extra": "^3.1.18",
    "puppeteer-extra-plugin-adblocker": "^2.11.11",
    "puppeteer-extra-plugin-block-resources": "^2.2.9",
    "puppeteer-extra-plugin-interceptor": "^0.2.2",
    "puppeteer-extra-plugin-stealth": "^2.7.6",
    "secret-agent": "^1.4.1-alpha.2"
  }
}

```

**Comment by blakebyrnes** [comment]
Thanks for reporting! 

Our agent.fetch function currently runs a browser-level "fetch" from inside a webpage context. Just like window.fetch. Our documentation is not doing a good job explaining that currently, you need to be on an actual webpage to run fetch. It's meant to replace ajax calls you'd want to make inside the page.

If you simply want to reduce the resource load of the requests, you can change your `agent.fetch` to `agent.goto`, and blockedResourceTypes to ["All"].

Can you tell me a bit more about what you were hoping for fetch to do?

**Comment by soermejo** [comment]
I wanted to make a request with the the same session (with cookies and headers) from the web page I was browsing. I have tried to do page.goto before that but I got the same error, maybe i should wait page to load?

**Comment by blakebyrnes** [comment]
You got an error when doing this?
```
import agent from 'secret-agent'

await agent.configure({
  blockedResourceTypes: ["BlockImages"],
});


(async () => {
        await agent.goto("https://127.0.0.1:8080")
	res = await agent.fetch("https://127.0.0.1:8080/px")
	console.log(res)
	await agent.close();
})();
```

**Comment by soermejo** [comment]
Ok no it works.

Il mar 20 apr 2021, 16:01 Blake Byrnes ***@***.***> ha
scritto:

**Comment by blakebyrnes** [comment]
Oh, ok, good. I'll improve the docs a bit, and we'll add an error if you try to fetch from a frame without an origin. Thanks!
