### ISSUE TITLE
TimeoutError: Timeout waiting for "tab.goto(https://google.com/)"'

### ISSUE THREAD

**Issue by TechnikMax** [ulixee/secret-agent#249]
When i try to run this script, first nothing happens and after a while the error above occurs. Then after an even longer time the secret agent and devtools opens with a blank page

```
const agent = require('secret-agent');

(async () => {
    await agent.goto('https://www.google.com/');
    console.log("yes")
    await agent.close();
})();

```

I used version 1.4.1-alpha.5 on Windows 10 

This is the full error message
```
2021-05-21T18:01:40.216Z ERROR [C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\@secret-agent\core\index] UnhandledErrorOrRejection {
  clientError: 'TimeoutError: Timeout waiting for "tab.goto(https://www.google.com/)"',
  context: {},
  sessionId: null,
  sessionName: undefined
} TimeoutError: Timeout waiting for "tab.goto(https://www.google.com/)"
    at Timer.waitForPromise (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\commons\Timer.ts:55:21)
    at Tab.goto (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\core\lib\Tab.ts:343:17)
    at CommandRecorder.runCommandFn (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\core\lib\CommandRecorder.ts:49:25)
    at Tab.CommandRecorder.owner.<computed> [as goto] (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\core\lib\CommandRecorder.ts:14:43)
    at ConnectionToClient.executeCommand (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\core\server\ConnectionToClient.ts:267:31)
    at ConnectionToClient.handleRequest (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\core\server\ConnectionToClient.ts:68:25)
    at WebSocket.<anonymous> (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\core\server\index.ts:95:27)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\ws\lib\websocket.js:835:20)
    at Receiver.emit (events.js:315:20)
------REMOTE CORE---------------------------------
    at Object.<anonymous> (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\commons\TypeSerializer.ts:63:28)
    at JSON.parse (<anonymous>)
    at Function.parse (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\commons\TypeSerializer.ts:24:17)
    at WebSocket.<anonymous> (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\client\connections\RemoteConnectionToCore.ts:67:42)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\ws\lib\websocket.js:835:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\ws\lib\receiver.js:437:14)
    at Receiver.getData (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\ws\lib\receiver.js:367:17)
    at Receiver.startLoop (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\ws\lib\receiver.js:143:22)
------CONNECTION----------------------------------
    at new Resolvable (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\commons\Resolvable.ts:17:18)
    at Object.createPromise (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\commons\utils.ts:39:10)
    at RemoteConnectionToCore.createPendingResult (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\client\connections\ConnectionToCore.ts:324:31)
    at RemoteConnectionToCore.internalSendRequestAndWait (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\client\connections\ConnectionToCore.ts:251:43)
    at RemoteConnectionToCore.sendRequest (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\client\connections\ConnectionToCore.ts:154:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.cb (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\client\lib\CoreCommandQueue.ts:37:26)
    at Queue.next (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\commons\Queue.ts:79:19)
------CORE COMMANDS-------------------------------
    at Queue.run (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\commons\Queue.ts:32:19)
    at CoreCommandQueue.run (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\client\lib\CoreCommandQueue.ts:36:8)
    at CoreTab.goto (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\client\lib\CoreTab.ts:83:36)
    at Tab.goto (C:\Users\xxx\WebstormProjects\test\untitled1\node_modules\client\lib\Tab.ts:140:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at C:\Users\xxx\WebstormProjects\test\untitled1\test1.js:20:5

--------------------------------------------------
------default-session-----------------------------
------859d9000-ba5e-11eb-9fd2-bb4e345703d7--------
-------------------------------------------------- {
  isDisconnecting: false
}
```

**Comment by janisblaus** [comment]
Check if you have 64bit node installed, I had the same issue and reinstalling with 64bit node.js and then reinstalling everything helped me with this issue.

**Comment by blakebyrnes** [comment]
@TechnikMax I don't see this timeout on Windows10 or on a Mac. Are you running this on a cloud computer or personal machine? This could be the IP you are coming from. SecretAgent doesn't do anything on it's own to change your IP if it's some thing google won't accept.

**Comment by blakebyrnes** [comment]
Closing this for inactivity. @TechnikMax if you have anything more to add I can re-open and investigate
