### ISSUE TITLE
Unable to use handlers in ubuntu

### ISSUE THREAD

**Issue by magicaltoast** [ulixee/secret-agent#282]
As in the title, I couldn't get the handler feature working on Linux (ubuntu).

**Env**
- Node: 16.4.2 (But 14.17.3 doesn't work either)
- OS: Ubuntu 21.04 (But on 20.04 doesn't work either)

**Minimal reproducible example**
```js
const { Handler } = require('secret-agent');
process.env.DEBUG = 'true';

const main = async () => {
    const handler = new Handler({ maxConcurrency: 16 })
    for (let i = 0; i < parseInt(process.argv[3]); i++) {
        handler.dispatchAgent(async (agent) => {
            console.log(i)
            await agent.goto(`https://discord.com`);
            await agent.waitForPaintingStable()
            await agent.waitForMillis(5000)
        })

    }
    await handler.close()
};

main().then(console.log)
```

**Error log**
```
2021-07-08T20:17:56.585Z INFO [/home/idk/token_harvester/node_modules/@secret-agent/core/index] Core.start { options: { maxConcurrency: 16 }, context: {} }
2021-07-08T20:17:56.588Z INFO [/home/idk/token_harvester/node_modules/@secret-agent/core/lib/GlobalPool] StartingGlobalPool { context: {} }
2021-07-08T20:17:56.611Z INFO [/home/idk/token_harvester/node_modules/@secret-agent/core/index] Core started { coreHost: 'ws://localhost:37219', context: {} }
2021-07-08T20:17:56.618Z INFO [/home/idk/token_harvester/node_modules/@secret-agent/mitm-socket/lib/CertificateGenerator] CertsIpcHandler.stdout: SessionArgs main.SessionArgs{IpcSocketPath:"/tmp/sa-ipc-certs-952d5870-e029-11eb-8281-4f699b25eaad.sock", RejectUnauthorized:false, ClientHelloId:"", TcpTtl:0, TcpWindowSize:0, Debug:true, Mode:"certs"}
 { context: {} }
2021-07-08T20:17:56.619Z INFO [/home/idk/token_harvester/node_modules/@secret-agent/mitm-socket/lib/CertificateGenerator] CertificateGenerator.onMessage {
  privateKey: some-key,
  status: 'init',
  context: {}
}
2021-07-08T20:17:56.628Z ERROR [/home/idk/token_harvester/node_modules/@secret-agent/client/connections/ConnectionFactory] Error connecting to core {
  error: 'DisconnectedFromCore: This Agent has been disconnected from Core (coreHost: undefined)',
  context: {},
  sessionId: null,
  sessionName: undefined
} DisconnectedFromCore: This Agent has been disconnected from Core (coreHost: undefined)
    at RemoteConnectionToCore.internalDisconnect (/home/idk/token_harvester/node_modules/client/connections/ConnectionToCore.ts:234:37)
    at RemoteConnectionToCore.disconnect (/home/idk/token_harvester/node_modules/client/connections/ConnectionToCore.ts:128:16)
    at /home/idk/token_harvester/node_modules/client/lib/Handler.ts:174:51
    at Array.map (<anonymous>)
    at Handler.close (/home/idk/token_harvester/node_modules/client/lib/Handler.ts:174:40)
    at main (/home/idk/token_harvester/index.js:15:19)
    at Object.<anonymous> (/home/idk/token_harvester/index.js:18:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32) {
  coreHost: undefined,
  code: 'DisconnectedFromCore'
}
```

**Comment by ctaity** [comment]
try with

```
const { Handler } = require('secret-agent');
process.env.DEBUG = 'true';

const main = async () => {
    const handler = new Handler({ maxConcurrency: 16 })
    for (let i = 0; i < parseInt(process.argv[3]); i++) {
        handler.dispatchAgent(async (agent) => {
            console.log(i)
            await agent.goto(`https://discord.com`);
            await agent.waitForPaintingStable()
            await agent.waitForMillis(5000)
        })
    }
 await handler.waitForAllDispatches();
 await handler.close();
};

main().then(console.log)

```

**Comment by blakebyrnes** [comment]
@ctaity is correct @magicaltoast. You need to wait for the work to be complete. Close is considered a "close now" operation. If you want to keep going regardless of errors, you can also do a `waitForAllDispatchesSettled`. `waitForAllDispatches` operates more like Promise.all.
