### ISSUE TITLE
Using ExecuteJsPlugin with dispatchAgent

### ISSUE THREAD

**Issue by ctaity** [ulixee/secret-agent#305]
```
import ExecuteJsPlugin from '@secret-agent/execute-js-plugin';

handler.dispatchAgent(async (agent: Agent) => {
      try {
        agent.use(ExecuteJsPlugin);
   
        const { activeTab, document } = agent;
        const { url } = agent.input;    
        const resource = await agent.goto(url);
       agent.waitForPaintingStable();
        // @ts-ignore
        const title = await agent.executeJs(() => {
          // @ts-ignore
          return window.document.title;
        });
```
and i get: 

```
 Error getting url: TypeError: agent.executeJs is not a function
      at /Users/taity/Work/sanbox/scrapper-proxy/src/index.ts:119:35
      at Generator.next (<anonymous>)
      at fulfilled (/Users/taity/Work/sanbox/scrapper-proxy/node_modules/tslib/tslib.js:107:62)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
```
What i doing wrong? 

I need to execute JS to resolve captchas. Thanks

**Comment by blakebyrnes** [comment]
@ctaity You're doing it right. We have a design flaw that means this can't currently work with handlers

**Comment by calebjclark** [comment]
@ctaity, as @blakebyrnes said, Handlers has a flaw with plugins. The solution is to drop Handler and just use PQueue with the Agent class.

An example:

```
import PQueue from 'p-queue';
import { Agent } from 'secret-agent';
import ExecuteJsPlugin from '@secret-agent/execute-js-plugin';

(async () => {
  async function createAndRunAgent(url) {
    const agent = new Agent();
    agent.use(ExecuteJsPlugin);

    const { activeTab, document } = agent;
    const resource = await agent.goto(url);
    agent.waitForPaintingStable();
    // @ts-ignore
    const title = await agent.executeJs(() => {
      // @ts-ignore
      return window.document.title;
    });
    console.log({ url, title });
    await agent.close();
  }

  const pqueue = new PQueue({ concurrency: 2 });
  const urls = ['https://news.ycombinator.com', 'https://example.org'];
  
  for (const url of urls) {
    pqueue.add(() => createAndRunAgent(url));
  }

  await pqueue.onIdle();
})();
```

**Comment by ctaity** [comment]
Ok no problem thanks!!!! @calebjclark @blakebyrnes !

**Comment by pzeepablo** [comment]
is this in the pipeline?
