### ISSUE TITLE
SA 1.5.4 runs out of heap after several thousand gotos

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#310]
Attaching 2 text files, the first is some logging from my test script showing the mem use as reported both by Node internally and by ps externally - the top 10 processes on the server ranked by RSS mem use. 3 log snippets there, from different points in the script run: after about 500 gotos, about 2k gotos, 4300 gotos just before it runs out of heap. The 2nd text file is just the console text from when it runs out of heap.

This is on Ubuntu 20.04, AWS t3.micro instance w/ 1 GB swap enabled.

The script does a series of 25 gotos (it does some xpath agent.document.evaluate stuff after each goto), then closes the agent and instantiates a new agent/session after first unlinking the prior session db.

[debug9.txt](https://github.com/ulixee/secret-agent/files/6890267/debug9.txt)
[debug8.txt](https://github.com/ulixee/secret-agent/files/6890268/debug8.txt)

**Comment by blakebyrnes** [comment]
@A-Posthuman What's your sense of what's going on here? Is this because Chrome processes aren't shutting down? Does anything jump out here at you?

**Comment by A-Posthuman** [comment]
Not an expert at debugging mem use, but just looking at the trend in the ps output from my debug9.txt file above, in the 3rd column (separated by semicolons in this output, the 3rd column is apparently the percentage of overall available system mem usage by each process), the "node_modules/@secret-agent/core/start.js" process climbs in percentage over time until the final reading is close to 40% of system mem (on this server that's 1 GB physical ram + 1 GB swap = 2 GB total).

By comparison the next largest process is a chrome process but over the course of the script's run its percentage of ram use stays pretty stable at around 5.6% of mem.

So the node process running start.js seems to be the bit really growing over time. I was trying to avoid this by closing and remaking my agent sessions periodically, but whatever is using up mem inside SA doesn't seem to release it. I guess I'll have to look into dividing up lengthy scraping sessions into chunks of maybe 1k urls at a time for the time being.

On the latest run of this script last night, the server actually locked up, I'm guessing again due to running out of mem. These mem issues may also be leading to some of the other odd errors and crashes I've seen after extended SA runs, but it's hard for me to say for sure.

**Comment by A-Posthuman** [comment]
Also, related to my other issue about SA's shutdown behavior, is there a way within my script after it has already started an agent, for it to trigger SA to completely shut down its processes and chrome, but without exiting my script? And then be able to restart SA afterwards. So to try to achieve a "reset" of the total SA system mem usage, but without going to the trouble to build in some extra shutdown/resume functionality into my script? Just looking to save myself some work if this is possible.

**Comment by emilio-cea** [comment]
We built your docker image (following the `Dockerfile` steps) and launched it with the `run_core_server.sh` and what we see is the memory of that container keeps increasing until it blows up and refuses to make connections anymore. Each call to the SA increments the memory usage by a rough 3-4 MB.

This is a snippet of how we are using the agent, we call `handler.dispatchAgent` which is initialized as `const handler = new Handler({ 
  host: process.env.SA_CORE_IP,
  maxConcurrency: 5
});`

Should we be closing something here? Is there any mistake?
```js
  async checkUser(@Param() params, @Res() res: Response) {
    this.handler.dispatchAgent(
      async (agent: Agent) => {
        agent.use(ExecuteJsPlugin);
        this.logger.log(`Checking user: ${params.user_id}`);
        const { activeTab, document } = agent;

        const url = buildUrl(MAIN_DOMAIN, {
          path: `@${params.user_id}`,
          queryParams: {
            lang: 'en',
          },
        });

        try {
          await agent.goto(MAIN_DOMAIN);
          await agent.waitForPaintingStable();

          this.logger.log('Navigating to:' + url);
          const source = await agent.goto(url);
          const statusCode = await source.response.statusCode;
          this.logger.log(statusCode);

          await activeTab.waitForLoad(LocationStatus.AllContentLoaded);
          const htmlSource = await document.documentElement.innerHTML;
          const html = parse(htmlSource);
          if (statusCode === HttpStatus.OK) {
            const sigi = await agent.executeJs(() => {
              return window['SIGI_STATE'];
            });
            const script = html.querySelector("script[id='__NEXT_DATA__']");
            if (sigi) {
              this.logger.debug("With SIGI");
              // this.logger.log("SIGI", sigi?.UserModule?.stats);
              // this.logger.log("SIGI", sigi?.UserModule);
              if (sigi?.UserModule?.stats) {
                this.logger.debug("Sent " + HttpStatus.OK);
                res.status(HttpStatus.OK).json({ status: statusCode });
                return;
              } else {
                this.logger.debug("Sent " + HttpStatus.NOT_FOUND);
                res.sendStatus(HttpStatus.NOT_FOUND);
                return;
              }
            } else if (script) {
              this.logger.debug("with script");
              const userInfo = JSON.parse(script?.text).props.pageProps.userInfo?.stats;
              // const userInfo = jsonInfo.props.pageProps.userInfo?.stats;
              // this.logger.log("script", typeof userInfo !== 'undefined', userInfo);
              if (typeof userInfo !== 'undefined' && userInfo) {
                this.logger.debug("Sent " + HttpStatus.OK);
                res.status(HttpStatus.OK).json({ status: statusCode });
                return;
              } else {
                this.logger.debug("Sent " + HttpStatus.NOT_FOUND);
                res.sendStatus(HttpStatus.NOT_FOUND);
                return;
              }
            } else {
              fs.writeFileSync(`./profiles/check_${params.user_id}.html`, htmlSource);

              this.logger.debug("with element");
              // const title = parse(await waitForSelector(agent, ".title", true, 4 * 1000));
              const errorDiv = await waitForSelector( // wait to see if the user exists
                agent,
                "div[class*='error-page']",
                false,
                5000,
              );
              if (errorDiv) {
                const textContent = await errorDiv.textContent;
                if (textContent.includes("Couldn't find this account")) {
                  this.logger.debug("Sent 404");
                  res.sendStatus(HttpStatus.NOT_FOUND);
                  return;
                }
              }
              let titleTest = await waitForSelector(agent, "head title", false, 4 * 1000);
              let titleContent = await titleTest.textContent;
              if (!titleContent?.length || titleContent?.contains("Couldn't find this account")) {
                // this.logger.log("bad title", title, title.text.length, title.text);
                this.logger.debug("Sent " + HttpStatus.NOT_FOUND);
                res.sendStatus(HttpStatus.NOT_FOUND);
                return;
              } else {
                this.logger.debug("Sent " + HttpStatus.OK);
                res.status(HttpStatus.OK).json({ status: statusCode });
                return;
              }
            }
          } else {
            this.logger.debug("Sent " + HttpStatus.NOT_FOUND);
            res.sendStatus(HttpStatus.NOT_FOUND);
          }
        } catch (e) {
          this.logger.error(e.stack);
          res.writeHead(HttpStatus.INTERNAL_SERVER_ERROR, 'Error with Secret Agent -> ' + e).end('Error with Secret Agent -> ' + e);
        }
      },
      {
        showReplay: false,
        blockedResourceTypes: ['BlockCssResources', 'BlockImages', 'BlockJsResources'],
        upstreamProxyUrl: UPSTREAM,
      },
    );
  }

```

**Comment by emilio-cea** [comment]
This is what appears on the console when we try to make more requests after the container runs out of memory

Edit: this is the error that shows when the browser container runs out of memory. First snippet is from the NestJS when more requests are made (you can see that when it runs out of memory the navigation fails), second are the logs from the docker container:

```
[Nest] 1  - 11/03/2021, 4:32:24 PM   ERROR [TikTokController] TypeError: Cannot read property 'goto' of null
    at Tab.goto (/usr/src/app/node_modules/client/lib/Tab.ts:160:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at handler.dispatchAgent.showReplay (/usr/src/app/src/tiktok.controller.ts:83:11)
    at /usr/src/app/node_modules/client/lib/Handler.ts:226:11
[Nest] 1  - 11/03/2021, 4:32:24 PM   ERROR [ExceptionsHandler] There are no active Core connections available.
Error: There are no active Core connections available.
    at Handler.getConnection (/usr/src/app/node_modules/client/lib/Handler.ts:255:36)
    at Handler.internalDispatchAgent (/usr/src/app/node_modules/client/lib/Handler.ts:209:29)
    at Handler.dispatchAgent (/usr/src/app/node_modules/client/lib/Handler.ts:95:10)
    at TikTokController.checkUser (/usr/src/app/src/tiktok.controller.ts:69:18)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
[Nest] 1  - 11/03/2021, 4:32:24 PM   ERROR [ExceptionsHandler] There are no active Core connections available.
Error: There are no active Core connections available.
    at Handler.getConnection (/usr/src/app/node_modules/client/lib/Handler.ts:255:36)
    at Handler.internalDispatchAgent (/usr/src/app/node_modules/client/lib/Handler.ts:209:29)
    at Handler.dispatchAgent (/usr/src/app/node_modules/client/lib/Handler.ts:95:10)
    at TikTokController.checkUser (/usr/src/app/src/tiktok.controller.ts:69:18)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
[Nest] 1  - 11/03/2021, 4:32:25 PM   ERROR [ExceptionsHandler] There are no active Core connections available.
Error: There are no active Core connections available.
    at Handler.getConnection (/usr/src/app/node_modules/client/lib/Handler.ts:255:36)
    at Handler.internalDispatchAgent (/usr/src/app/node_modules/client/lib/Handler.ts:209:29)
    at Handler.dispatchAgent (/usr/src/app/node_modules/client/lib/Handler.ts:95:10)
    at TikTokController.checkUser (/usr/src/app/src/tiktok.controller.ts:69:18)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by emilio-cea** [comment]
And this appears on the container logs when it runs out of memory:

```
2021-11-03T16:32:23.873Z INFO [core/lib/GlobalPool] AcquiringChrome { maxConcurrentAgentsCount: 10, context: {} }
2021-11-03T16:32:23.877Z INFO [core/lib/Session] Dynamically requiring @secret-agent/execute-js-plugin requested by @secret-agent/execute-js-plugin { context: { sessionId: '9fca0930-3cc3-11ec-9e7b-eb94c6d1a07b' } }
2021-11-03T16:32:23.997Z INFO [mitm-socket/lib/MitmSocketSession] ProxyIpcHandler.stdout: [id=8724] Read 3048 bytes from remote. Total: 159165
[id=8736] Read 0 bytes from client. Total: 485
[id=8736] Read 0 bytes from remote. Total: 5205
[id=8729] Read 0 bytes from client. Total: 654
 { context: { sessionId: '8f20e630-3cc3-11ec-9e7b-eb94c6d1a07b' } }
2021-11-03T16:32:24.005Z ERROR [core/index] UnhandledError(fatal) {
  clientError: 'Error: spawn ENOMEM',
  context: {},
  sessionId: null,
  sessionName: undefined
} Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:405:11)
    at spawn (child_process.js:677:9)
    at Object.spawnWithSignal [as spawn] (child_process.js:911:17)
    at MitmSocketSession.spawnChild (/app/mitm-socket/lib/BaseIpcHandler.ts:179:18)
    at /app/mitm-socket/lib/BaseIpcHandler.ts:60:12
    at FSReqCallback.oncomplete (fs.js:179:23) {
  errno: -12,
  code: 'ENOMEM',
  syscall: 'spawn'
}
2021-11-03T16:32:24.015Z STATS [puppet/lib/launchProcess] Chrome.ProcessExited { context: {} }
2021-11-03T16:32:24.016Z INFO [core/lib/Session] Session.Closing { context: {} }
2021-11-03T16:32:24.017Z INFO [core/index] Core.shutdown { context: {} }
2021-11-03T16:32:24.017Z STATS [core/server/ConnectionToClient] ConnectionToClient.Disconnecting { context: {} }
2021-11-03T16:32:24.018Z STATS [commons/ShutdownHandler] ShutdownHandler.onSignal { signal: 'exit', context: {} }
2021-11-03T16:32:24.022Z STATS [commons/ShutdownHandler] ShutdownHandler.execute {
  signal: 'exit',
  fn: 'async function close() {\n' +
    '        try {\n' +
    "            // attempt graceful close, but don't wait\n" +
    '            if (transport) {\n' +
    "                transport.end(JSON.stringify({ method: 'Browser.close', id: -1 }));\n" +
    '            }\n' +
    '            if (!launchedProcess.killed && !processKilled) {\n' +
    "                const closed = new Promise(resolve => launchedProcess.once('exit', resolve));\n" +
    "                if (process.platform === 'win32') {\n" +
    '                    childProcess.execSync(`taskkill /pid ${launchedProcess.pid} /T /F 2> nul`);\n' +
    '                }\n' +
    '                else {\n' +
    "                    launchedProcess.kill('SIGKILL');\n" +
    '                }\n' +
    "                launchedProcess.emit('exit');\n" +
    '                await closed;\n' +
    '            }\n' +
    '        }\n' +
    '        catch (error) {\n' +
    '            // might have already been kill off\n' +
    '        }\n' +
    '    }',
  callsite: 'at Object.launchProcess [as default] (/app/puppet/lib/launchProcess.ts:104:19)',
  context: {}
}
internal/child_process.js:405
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:405:11)
    at spawn (child_process.js:677:9)
    at Object.spawnWithSignal [as spawn] (child_process.js:911:17)
    at MitmSocketSession.spawnChild (/app/mitm-socket/lib/BaseIpcHandler.ts:179:18)
    at /app/mitm-socket/lib/BaseIpcHandler.ts:60:12
    at FSReqCallback.oncomplete (fs.js:179:23) {
  errno: -12,
  code: 'ENOMEM',
  syscall: 'spawn'
}
```

**Comment by tienne** [comment]
Is there anything related to the issue?
Whenever I run with a handler, the core-side memory gradually increases, and there is an issue that the core server shuts down due to a lack of memory.

**Comment by blakebyrnes** [comment]
No update yet. Would love help with a simple test script and/or a list of what's left in memory (not getting cleaned up) if you are able to help

**Comment by azamsolix** [comment]
Hi,
I am also facing same issue. Is there any update on this issue?

**Comment by emilio-cea** [comment]
> No update yet. Would love help with a simple test script and/or a list of what's left in memory (not getting cleaned up) if you are able to help

Hi @blakebyrnes, here's a simple test script similar to other (longer) controllers that we are using. We are closing the agent here so we don't know if we should make any cleanup as well. Any pointers for this kind of procedure, is everything ok here?
```js
// eslint-disable-next-line @typescript-eslint/no-var-requires
const buildUrl = require('build-url');
import {
  Controller,
  Logger,
  Get,
  HttpStatus,
  Res,
} from '@nestjs/common';
import { Handler, LocationStatus } from 'secret-agent';
import { Response } from 'express';
import { ApiResponse, ApiTags } from '@nestjs/swagger';


@ApiTags('Healthcheck')
@Controller('healthcheck')
export class HealthcheckController {
  private readonly logger = new Logger(HealthcheckController.name);

  constructor(private readonly handler: Handler) { }

  @Get()
  @ApiResponse({
    status: 200,
    description: 'Tests the navigation finishes successfully',
  })
  async health(@Res() res: Response) {
    const uri = buildUrl('https://example.org/');
    const agent = await this.handler.createAgent();
    try {
      this.logger.log('Navigating to:' + uri);
      await agent.goto(uri);
      this.logger.log('Waiting all content');
      await agent.activeTab.waitForLoad(LocationStatus.AllContentLoaded);
      const content = await agent.document.querySelector('body > div > h1')
      if ((await content.innerText).includes("Example Domain")){
        this.logger.debug("Scraped content correctly")
        res.sendStatus(HttpStatus.OK);
      } else {
        res.writeHead(HttpStatus.INTERNAL_SERVER_ERROR, 'Internal Server Error - Healthcheck failed').end('Internal Server Error - Healthcheck failed');
      }
      return;
    } catch (e) {
      this.logger.error(e.stack);
      res.writeHead(HttpStatus.INTERNAL_SERVER_ERROR, 'Error with Secret Agent -> ' + e).end('Error with Secret Agent -> ' + e);
    } finally {
      await agent.close();
    }
  }
}
```

As for the memory on the Core, we adapted the Dockerfile to run inside a container and we cannot access it to execute commands inside as of yet. Any pointers as to what to look for?

**Comment by blakebyrnes** [comment]
Thanks @emilio-cea. I can translate this to something simple. Are you seeing the memory leak if you ONLY call this single api?

Regarding your question above - you're cleaning up the agents as expected. Some people have written scripts to cleanup the Session databases that are generated on some period (http://secretagent.dev/docs/advanced/session/)

Are you running Core on a different docker than your API above? You'll want to run start a Core server in that process and then point your handler to the port you start it on (https://secretagent.dev/docs/advanced/remote)

**Comment by emilio-cea** [comment]
> Thanks @emilio-cea. I can translate this to something simple. Are you seeing the memory leak if you ONLY call this single api?  

I CURLed 100 times this endpoint and noticed the memory increase/decrease per execution and, after finishing, the memory stayed increased. Should it be released instantly?.
I noticed that if I keep launching CURLs at it some memory frees but keeps adding up eventually

> Regarding your question above - you're cleaning up the agents as expected. Some people have written scripts to cleanup the Session databases that are generated on some period (http://secretagent.dev/docs/advanced/session/)

Yes, we also  faced this issue 👍

> Are you running Core on a different docker than your API above? You'll want to run start a Core server in that process and then point your handler to the port you start it on (https://secretagent.dev/docs/advanced/remote)

We are running them on separate machines yes. We pointed the API to the core IP and port correctly. On the `app.module` file we use:
```js
const handler = new Handler({ 
  host: process.env.SA_CORE_IP,
  maxConcurrency: Number(process.env.SA_CONCURRENCY) // currently 5
});
```

We aren't using the Replay functionality either (although I don't know if it could be related)

**Comment by blakebyrnes** [comment]
Mileage may vary on this one. I found that it was not cleaning up SecretAgent sessions properly, so fixed that. NOTE: you will still see small memory increases as cached DNS lookups accumulate in memory, but it should be significantly reduced. 

To any testers, this is in version 1.6.3. Let me know what you see (discord or here is fine).
