### ISSUE TITLE
TimeoutError: Timeout waiting for element to be visible

### ISSUE THREAD

**Issue by janisblaus** [ulixee/secret-agent#326]
```
const {Agent,XPathResult} = require('secret-agent');

process.env.SA_SHOW_BROWSER = 'true';

(async () => {

  const agentConfig = {
    name: `Agent-example-1`,
    showReplay: true,
    sessionsDir: 'session',
  };

  const agent = await new Agent(agentConfig);

  await facebook(agent);

})();

async function facebook(agent){
	await agent.goto('https://facebook.com/');

	await agent.waitForPaintingStable();

	console.log(`Domain loaded - ${await agent.document.title}`);

	await agent.waitForElement(agent.document.querySelector('button[data-cookiebanner="accept_button"]'), { waitForVisible: true, timeout: 4 });

	const button = await agent.document.querySelector('button[data-cookiebanner="accept_button"]');
  
	await agent.click(button);
}

```

![image](https://user-images.githubusercontent.com/1029697/129304483-1f51dd4e-ddf5-4845-ac2e-81f8f3071beb.png)

**Comment by blakebyrnes** [comment]
The timeout variables should be timeoutMs and in milliseconds, but that means it should have just timed out after 30 seconds. Is the element "visible"? If you're wanting to just "see" if it's visible for up to 4 seconds, you need to try/catch around it.

**Comment by janisblaus** [comment]
element is visible, it's a cookie popup, tried all ways around it, did not work

**Comment by janisblaus** [comment]
Same problem with other sites, seems that ones using js frameworks are affected, secret agent do not see that popups are open and visible to the user

**Comment by janisblaus** [comment]
after extended testing I found out that xpath works, it can select the element. 

```const result = await this.agent.document.evaluate(xpath,this.agent.document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null);

await this.agent.waitForElement(result.singleNodeValue, { timeout: 5000 });
```

And then I can click on element by using result.singleNodeValue.click();

But it then executes this javascript based click that does not allow popups to be opened. (facebook login button)

**Comment by blakebyrnes** [comment]
If you try a waitForElement (without waitForVisible) and then you do a getComputedVisibility on the item, does it tell you more about why it thinks the element isn’t visible?

**Comment by janisblaus** [comment]
I made sure element is really there and there are no hidden duplicated by opening the console and running
document.querySelector('button[aria-label="Log in with Facebook"]') it works fine and selects the right element.

getComputedVisibility gives me this:

```
{
  isVisible: false,
  nodeExists: true,
  isConnected: true,
  hasContainingElement: true,
  hasCssVisibility: true,
  hasCssDisplay: true,
  hasCssOpacity: true,
  isUnobstructedByOtherElements: false,
  obstructedByElementId: 689,
  boundingClientRect: { y: 382.671875, x: 544, height: 54, width: 352, tag: 'button' },
  hasDimensions: true,
  isOnscreenVertical: true,
  isOnscreenHorizontal: true
}


```

**Comment by blakebyrnes** [comment]
So it looks like secret agent thinks there's an element on top of this button that covers it up. Is there something that covers the button that could be going away on hover in your browser?

**Comment by janisblaus** [comment]
There are no other elements covering it.

Spent hours on this and still cant find how to solve it.

Ive attached a very short code example in my first message.

**Comment by blakebyrnes** [comment]
@janisblaus Can you send over your session db for this one?

**Comment by janisblaus** [comment]
Sure, attaching it. 
[sessions.zip](https://github.com/ulixee/secret-agent/files/7071319/sessions.zip)

**Comment by blakebyrnes** [comment]
This session looks like it actually didn't surface a bad query selector. If I re-run your original script it's working correctly for me. Can you send that session?

**Comment by janisblaus** [comment]
Sorry, after so much testing, I probably added the wrong file :( 

I recreated everything again. 

![image](https://user-images.githubusercontent.com/1029697/131232395-331faf29-c542-4c27-901f-363b934a65cb.png)


[ced8ee30-084d-11ec-8359-8d6faae08c67.zip](https://github.com/ulixee/secret-agent/files/7071575/ced8ee30-084d-11ec-8359-8d6faae08c67.zip)

**Comment by janisblaus** [comment]
This issue is still there @blakebyrnes 

Tested with secret agent 1.5.13 on windows 10.

Here is a simplified example:

```
const {Agent,XPathResult} = require('secret-agent');

process.env.SA_SHOW_BROWSER = 'true';

(async () => {

  const agentConfig = {
    name: `Agent-example-1`,
    showReplay: true,
    sessionsDir: 'session',
  };

  const agent = await new Agent(agentConfig);

  await youtube(agent);

})();

async function youtube(agent){
	await agent.goto('https://www.youtube.com/');

	await agent.waitForPaintingStable();

	console.log(`Domain loaded - ${await agent.document.title}`);

  const button  = agent.document.querySelector('[aria-label="Agree to the use of cookies and other data for the purposes described"]');
  const button2 = agent.document.querySelector('ytd-thumbnail:first-child');

  //console.log(await agent.getComputedVisibility(button))

  try {
    console.log('Trying to locate and click terms button')
    await agent.waitForElement(button, { waitForVisible: true });
    await agent.click(button);

    console.log('Trying to locate and click first thumbnail')
    await agent.waitForElement(button2, { waitForVisible: true });
    await agent.click(button2);


  }catch(e){
    console.log('Could not click the button', e)
    console.log(await agent.getComputedVisibility(button))
    console.log(await agent.getComputedVisibility(button2))
  }
}

```

getComputedVisibility: 
(first isVisible: false is correct because button is clicked correctly, problem is with button2 )
```
{
  isVisible: false,
  nodeExists: true,
  isConnected: true,
  hasContainingElement: true,
  hasCssVisibility: true,
  hasCssDisplay: true,
  hasCssOpacity: true,
  isUnobstructedByOtherElements: false,
  obstructedByElementId: 408,
  boundingClientRect: { y: 0, x: 0, height: 0, width: 0, tag: 'tp-yt-paper-button' },
  hasDimensions: false,
  isOnscreenVertical: false,
  isOnscreenHorizontal: false
}
{
  isVisible: false,
  nodeExists: true,
  isConnected: true,
  hasContainingElement: true,
  hasCssVisibility: true,
  hasCssDisplay: true,
  hasCssOpacity: true,
  isUnobstructedByOtherElements: false,
  obstructedByElementId: 6331,
  boundingClientRect: { y: 756, x: 996, height: 44, width: 78, tag: 'ytd-thumbnail' },
  hasDimensions: true,
  isOnscreenVertical: true,
  isOnscreenHorizontal: true
}
```

Trace:

```
2021-11-03T00:59:37.428Z ERROR [C:\projects\youtube\worker\node_modules\@secret-agent\core\lib\Interactor] Interaction.click - mousePosition not in viewport after mouse moves to prepare for click. {
  'Interaction.mousePosition': [ 'document', [ 'querySelector', 'ytd-thumbnail:first-child' ] ],
  target: {
    nodeId: 671,
    nodeVisibility: {
      isVisible: false,
      nodeExists: true,
      isConnected: true,
      hasContainingElement: true,
      hasCssVisibility: true,
      hasCssDisplay: true,
      hasCssOpacity: true,
      isUnobstructedByOtherElements: false,
      obstructedByElementId: 6331,
      boundingClientRect: { y: 756, x: 996, height: 44, width: 78, tag: 'ytd-thumbnail' },
      hasDimensions: true,
      isOnscreenVertical: true,
      isOnscreenHorizontal: true
    },
    domCoordinates: { x: 1045, y: 783 }
  },
  viewport: {
    positionX: 15,
    positionY: 40,
    screenWidth: 1440,
    screenHeight: 900,
    width: 1424,
    height: 826,
    deviceScaleFactor: 1
  },
  context: { sessionId: '48059930-3c41-11ec-a34e-a9b23136b62c', frameId: 1 },
  sessionId: '48059930-3c41-11ec-a34e-a9b23136b62c',
  sessionName: 'agent-example-1'
}



Could not click the button Error: Element or mousePosition remains out of viewport after 2 attempts to move it into view
    at DefaultHumanEmulator.moveMouseAndClick (C:\projects\youtube\worker\plugins\default-human-emulator\index.ts:196:13)
    at DefaultHumanEmulator.playInteractions (C:\projects\youtube\worker\plugins\default-human-emulator\index.ts:75:11)
    at CorePlugins.playInteractions (C:\projects\youtube\worker\node_modules\core\lib\CorePlugins.ts:189:7)
------REMOTE CORE---------------------------------
    at Function.reviver (C:\projects\youtube\worker\node_modules\commons\TypeSerializer.ts:208:26)
    at JSON.parse (<anonymous>)
    at Function.parse (C:\projects\youtube\worker\node_modules\commons\TypeSerializer.ts:24:17)
    at WebSocket.<anonymous> (C:\projects\youtube\worker\node_modules\client\connections\RemoteConnectionToCore.ts:67:42)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (C:\projects\youtube\worker\node_modules\ws\lib\websocket.js:983:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (C:\projects\youtube\worker\node_modules\ws\lib\receiver.js:517:14)
    at C:\projects\youtube\worker\node_modules\ws\lib\receiver.js:468:23
    at C:\projects\youtube\worker\node_modules\ws\lib\permessage-deflate.js:308:9
------CONNECTION----------------------------------
    at new Resolvable (C:\projects\youtube\worker\node_modules\commons\Resolvable.ts:17:18)
    at Object.createPromise (C:\projects\youtube\worker\node_modules\commons\utils.ts:68:10)
    at RemoteConnectionToCore.createPendingResult (C:\projects\youtube\worker\node_modules\client\connections\ConnectionToCore.ts:328:31)
    at RemoteConnectionToCore.internalSendRequestAndWait (C:\projects\youtube\worker\node_modules\client\connections\ConnectionToCore.ts:253:43)
    at RemoteConnectionToCore.sendRequest (C:\projects\youtube\worker\node_modules\client\connections\ConnectionToCore.ts:156:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.cb (C:\projects\youtube\worker\node_modules\client\lib\CoreCommandQueue.ts:104:26)
    at Queue.next (C:\projects\youtube\worker\node_modules\commons\Queue.ts:82:19)
------CORE COMMANDS-------------------------------
    at Queue.run (C:\projects\youtube\worker\node_modules\commons\Queue.ts:35:19)
    at CoreCommandQueue.run (C:\projects\youtube\worker\node_modules\client\lib\CoreCommandQueue.ts:100:8)
    at CoreFrameEnvironment.interact (C:\projects\youtube\worker\node_modules\client\lib\CoreFrameEnvironment.ts:72:29)
    at Function.run (C:\projects\youtube\worker\node_modules\client\lib\Interactor.ts:47:21)
    at Agent.click (C:\projects\youtube\worker\node_modules\client\lib\Agent.ts:286:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at youtube (C:\projects\youtube\worker\youtube.js:38:5)
    at C:\projects\youtube\worker\youtube.js:15:3
[1f1f0470-3c41-11ec-ad68-d78f4269f981.zip](https://github.com/ulixee/secret-agent/files/7464805/1f1f0470-3c41-11ec-ad68-d78f4269f981.zip)

--------------------------------------------------
------agent-example-1-----------------------------
------1f1f0470-3c41-11ec-ad68-d78f4269f981--------
--------------------------------------------------
```

If I skip clicking the first button and only try to click the thumbnail, it gives element visible timeout.
