### ISSUE TITLE
ability to monitor resource request and see when a font url is requested

### ISSUE THREAD

**Issue by andynuss** [ulixee/secret-agent#359]
I have a need somewhat related to issue 338.

The general need is simply to intercept every single resource request that Chrome makes.
Here the goal is not to change anything, but just get information, in this case, specifically
about what (web) fonts are being requested by the browser when it visits the page.

In puppeteer, I was doing this:

    const fontList = [];

    ...

    page.on('request', (request) => {
      const type = request.resourceType();
      const url = request.url();
      const isdata = url.startsWith('data:');
      if (type === 'font' && !isdata) {
        // fontList is a list of all (web) fonts ACTUALLY dynamically loaded
        // by Chrome based on seeing that a css file used by either the
        // main page or a child iframe needs it.
        fontList.push(url);
      }
    });

... where the goal, in addition to scraping the outerHTML of the webpage, it is also to get a list
of (web) fonts which actually had to be loaded by the browser, such as for an @font-face css
rule that fired as the page was being displayed.

I can't seem to find any way to do this with secret-agent.

**Comment by blakebyrnes** [comment]
I think you’re looking for tab.on(‘resource’, event => …

https://secretagent.dev/docs/basic-interfaces/tab#resource-event

You can wait for a specific resource as well with ‘waitForResource’. Not sure what flow you want here - ie, just passively listen, or block until your resource shows up

**Comment by andynuss** [comment]
I believe it is possible I may have found a bug with this snippet:

    const tabs: Tab[] = await myagent.tabs;
    for (const tab of tabs) {
      tab.on('resource', (event) => {
        if (event.request) {
          event.request.headers.then((headers) => {
            if (headers['sec-fetch-dest'] === 'font') {
              event.request.url.then(url => {
                console.log('fonturl', url);
              })
            }
          });
        }
      });
    }

This does work on its own, but my custom plugin for injected javascript evaluation subsequently fails.

    // @ts-ignore
    const data = await myagent.evaluate(0, (a, b, c) => {
      // @ts-ignore
      return [document.documentElement.outerHTML, a, b, c];
    }, rootOptions, 'a', 'bb', 'ccc');
    console.log('data', data);

This is essentially the same code for an injected plugin that we got to work earlier, which I call only after the page
has finished loading.  As long as I don't execute the first code snippet to intercept resources, my plugin code
does work.  But it turns out that simply executing the following (which I must do before I "goto" my page url)
is enough to cause my plugin/evaluate call to return the undefined value:

    const tabs: Tab[] = await myagent.tabs;

**Comment by andynuss** [comment]
I found the fix:

    const tab: Tab = myagent.activeTab;
    tab.on('resource', (event) => {
      if (event.request) {
        event.request.headers.then((headers) => {
          if (headers['sec-fetch-dest'] === 'font') {
            event.request.url.then(url => {
              fontList.push(url);
            })
          }
        });
      }
    });

One question I have is whether attaching the resource event listener to my agent instance's activeTab
before use agent.goto() to load the page will still ensure that I see all the child iframe resources for
this page.

**Comment by blakebyrnes** [comment]
I believe that should work fine to get all child frame resources too. Also, there's a top level "resourceType" field on the resource event that should return Font it Chrome thinks it's a font (your approach also works great).

Should I close this one?

**Comment by andynuss** [comment]
Well, I found a small bug with attaching a listener to the activeTab as I did above.  It turns out that this probably shows up since I close my newly created agent right after the scrape, and there seems to be a need to delay a few millis after my last evaluate of the loaded page, and before closing the newly created agent, which is caught and logged internally by secret-agent (i.e. it is AFTER all my lines of code has executed):

     2021-10-02T18:02:30.321Z ERROR [/home/ec2-user/app/node_modules/@secret-agent/core/index] UnhandledErrorOrRejection {
    1|server   |   clientError: 'DisconnectedFromCore: This Agent has been disconnected from Core (coreHost: ws://localhost:40315)',
    1|server   |   context: {},
    1|server   |   sessionId: null,
    1|server   |   sessionName: undefined
    1|server   | } DisconnectedFromCore: This Agent has been disconnected from Core (coreHost: ws://localhost:40315)
    1|server   |     at RemoteConnectionToCore.onResponse (/home/ec2-user/app/node_modules/client/connections/ConnectionToCore.ts:305:25)
    1|server   |     at RemoteConnectionToCore.onMessage (/home/ec2-user/app/node_modules/client/connections/ConnectionToCore.ts:166:12)
    1|server   |     at WebSocket.<anonymous> (/home/ec2-user/app/node_modules/client/connections/RemoteConnectionToCore.ts:68:16)
    1|server   |     at WebSocket.emit (events.js:400:28)
    1|server   |     at WebSocket.emit (domain.js:475:12)
    1|server   |     at Receiver.receiverOnMessage (/home/ec2-user/app/node_modules/ws/lib/websocket.js:983:20)
    1|server   |     at Receiver.emit (events.js:400:28)
    1|server   |     at Receiver.emit (domain.js:475:12)
    1|server   |     at Receiver.dataMessage (/home/ec2-user/app/node_modules/ws/lib/receiver.js:517:14)
    1|server   |     at /home/ec2-user/app/node_modules/ws/lib/receiver.js:468:23
    1|server   | ------CONNECTION----------------------------------
    1|server   |     at new Resolvable (/home/ec2-user/app/node_modules/commons/Resolvable.ts:17:18)
    1|server   |     at Object.createPromise (/home/ec2-user/app/node_modules/commons/utils.ts:68:10)
    1|server   |     at RemoteConnectionToCore.createPendingResult (/home/ec2-user/app/node_modules/client/connections/ConnectionToCore.ts:328:31)
    1|server   |     at RemoteConnectionToCore.internalSendRequestAndWait (/home/ec2-user/app/node_modules/client/connections/ConnectionToCore.ts:253:43)
    1|server   |     at RemoteConnectionToCore.sendRequest (/home/ec2-user/app/node_modules/client/connections/ConnectionToCore.ts:156:17)
    1|server   |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
    1|server   |     at Object.cb (/home/ec2-user/app/node_modules/client/lib/CoreCommandQueue.ts:104:26)
    1|server   |     at Queue.next (/home/ec2-user/app/node_modules/commons/Queue.ts:82:19)
    1|server   | ------CORE COMMANDS-------------------------------
    1|server   |     at Queue.run (/home/ec2-user/app/node_modules/commons/Queue.ts:35:19)
    1|server   |     at CoreCommandQueue.run (/home/ec2-user/app/node_modules/client/lib/CoreCommandQueue.ts:100:8)
    1|server   |     at CoreTab.getResourceProperty (/home/ec2-user/app/node_modules/client/lib/CoreTab.ts:84:36)
    1|server   |     at /home/ec2-user/app/node_modules/client/lib/ResourceRequest.ts:64:36
    1|server   | 
    1|server   | --------------------------------------------------
    1|server   | ------default-session-2---------------------------
    1|server   | ------dc13cb60-23aa-11ec-bbb3-6bc09054af2f--------
    1|server   | -------------------------------------------------- {
    1|server   |   coreHost: 'ws://localhost:40315',
    1|server   |   code: 'DisconnectedFromCore'
    1|server   | }

I create my agent with this code:

    const ua = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.165 Safari/537.36';

    let sharedConnection: ConnectionToCore = null;

    function getConnection (): ConnectionToCore {
      if (sharedConnection !== null) return sharedConnection;
      sharedConnection = ConnectionFactory.createConnection({
        maxConcurrency: 4,
      });
      return sharedConnection;
    }

    export function newAgent(): Agent {
      return new Agent({
        userAgent: ua,
        viewport: {
          screenHeight: 768,
          screenWidth: 1024,
          height: 768,
          width: 1024,
        },
        connectionToCore: getConnection(),
      });
    }

and I need to do a sleep as follows in my server code to avoid this:

    function sleep(millis) {
      return new Promise((resolve) => setTimeout(resolve, millis));
    }

    async function CloseAgent() {
      const agent2 = agent;
      if (!agent2) return;
      agent = null;
    
      // seems like sleeping 20 millis is usually enough to avoid the
      // error that is thrown, caught and logged by secret-agent
      await sleep(20);
    
      try {
        await agent2.close();
      } catch (e) {
        console.log('unexpected error closing Agent', e);
      }
      
      // if we do NOT do the sleep above, then the error thrown,
      // caught and logged by secret-agent comes AFTER the above
      // has completed
    }

    async function ScrapeCloseAndReturn(requestUrl, imageName) {
      try {
        agent = newAgent();
        const gotoMillis = [0];
        const evalMillis = [0];
        const dom = await scrapeDom(agent, config.gotoTimeout, requestUrl, imageName, gotoMillis, evalMillis);
        await CloseAgent();
        SuccessScrapeResponse(res, {
          rootDom: dom,
          screenshot: null,                 //  TODO: implement this when secret-agent issue 322 is resolved
          gotoMillis: gotoMillis[0],
          evaluateMillis: evalMillis[0],
        });
      } catch (e) {
        await CloseAgent();
        if (e instanceof GotoTimeoutError)
          ErrorCodeResponse(res, ERROR_GOTO_TIMEOUT, null);
        else
          ErrorCodeResponse(res, ERROR_SERVER_EXCEPTION, '' + e, '' + e.stack);
      }
    }

**Comment by blakebyrnes** [comment]
It looks like you’re accessing properties of a resource after you close the agent down - but hard to tell since you didn’t include that part of your code. Continuing to request properties of an agent’s resources would trigger this error. You should either grab the resource properties before you pass them into SuccessScrapeResponse or await the SuccessScrapeResponse before close.

**Comment by andynuss** [comment]
In the code above, the function scrapeDom(), which I await in ScrapeCloseAndReturn, is the function that contains the entirety of my own code.  However, that code includes the following that you showed me for intercepting resources:

    activeTab.on('resource', (event) => {
      ...
    }

The point is that when scrapeDom finishes all its work (capturing html and stylesheets), it returns, and then its
caller, which is ScrapeCloseAndReturn, wants to close my dynamically created agent right away, but it turns out
that my resource listener attached by activeTab.on('resource', ...) must still be firing away for some pages, and
I even tried using activeTab.off('resource', ...) to no avail.  It looks like I've got to delay before closing the agent,
sometimes by as much as a full second, to avoid secret-agent getting these internally logged errors that happen AFTER
all my code is finished, and AFTER the agent is closed.

Again, these errors seem harmless to me, since they are after my code is run, but it is concerning.

One request url that seems to be require that I sleep for a full second to prevent these unwanted errors is:

https://www.theatlantic.com/technology/archive/2018/05/electric-scooters-are-the-cargo-shorts-of-transportation/561440/?single_page=true

**Comment by blakebyrnes** [comment]
Can you provide a full code example that is failing? It's very hard to piece together what's going on without the smaller details

**Comment by andynuss** [comment]
Give me some time to put together a reproducible case.

**Comment by andynuss** [comment]
Hi Blake, just sent 2 typescript files to you.

**Comment by andynuss** [comment]
I just now checked my example, and the bug is still reproducible (most of the time) by running the compiled version of scraper.js from the command line, against 1.5.12.

Were you not able to reproduce it from the scraper.ts and plugin.ts that I sent you?
