### ISSUE TITLE
How to extend default browser emulator

### ISSUE THREAD

**Issue by janisblaus** [ulixee/secret-agent#360]
I've created newBrowserEmulator.js

```
let defaultBrowserEmulator = require('@secret-agent/default-browser-emulator').default;
const { PluginTypes } = require('@secret-agent/interfaces/IPluginTypes');

let newBrowserEmulator = class newBrowserEmulator extends defaultBrowserEmulator{
	static id = 'newBrowserEmulator';
	static type = PluginTypes.BrowserEmulator;

	static onBrowserWillLaunch(browserEngine, options) {
		console.log(browserEngine, options);
	}
}

exports.default = newBrowserEmulator;
exports.latestChromeBrowserVersion = void 0;
exports.latestBrowserEngineId = 'chrome-88-0';
exports.latestChromeBrowserVersion = { major: '88', minor: '0' };
```

Then I try to set it as 

```
new Agent({browserEmulatorId: 'newBrowserEmulator'});
```

And pass as a plugin as well:

```
const newBrowserEmulator = require('./newBrowserEmulator');
agent.use(newBrowserEmulator );
```

Everything fails with:

```
ERROR FROM INITALIZE Error: Cannot find module 'newBrowserEmulator'
Require stack:
- \worker\node_modules\@secret-agent\plugin-utils\lib\utils\requirePlugins.js
- \worker\node_modules\@secret-agent\core\index.js
- \worker\node_modules\@secret-agent\core\start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.requirePlugins [as default] (\worker\node_modules\plugin-utils\lib\utils\requirePlugins.ts:18:37)
    at new CorePlugins (\worker\node_modules\core\lib\CorePlugins.ts:71:39)
    at new Session (\worker\node_modules\core\lib\Session.ts:105:20)
    at Function.createSessionNow (\worker\node_modules\core\lib\GlobalPool.ts:137:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ConnectionToClient.createSession (\worker\node_modules\core\server\ConnectionToClient.ts:212:21)
```

**Comment by blakebyrnes** [comment]
In the current SecretAgent setup, Core runs in a forked process, so it won't see your plugin activation unless you install the plugin on the "server". If this is all on one machine, take a look at this example for a way to use paths instead of the module: https://github.com/ulixee/secret-agent/blob/main/examples/plugin-echo-use.ts

**Comment by blakebyrnes** [comment]
@janisblaus can I close this one?
