### ISSUE TITLE
Checksum error installing on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by wackyworm** [ulixee/secret-agent#371]
pi@raspberrypi:~/dev-node/apeswap-pools $ npm i secret-agent
npm ERR! code 1
npm ERR! path /home/pi/dev-node/apeswap-pools/node_modules/@secret-agent/mitm-socket
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Could not install MitmSocket library Error: Invalid checksum found for Secret Agent MitmSocket library
npm ERR!     at getSourceChecksum (/home/pi/dev-node/apeswap-pools/node_modules/@secret-agent/mitm-socket/install.js:134:15)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR!     at async install (/home/pi/dev-node/apeswap-pools/node_modules/@secret-agent/mitm-socket/install.js:27:22)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-11-10T08_42_19_194Z-debug.log

pi@raspberrypi:~/dev-node/apeswap-pools $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

pi@raspberrypi:~/dev-node/apeswap-pools $ uname -m
armv7l

[2021-11-10T08_42_19_194Z-debug.log](https://github.com/ulixee/secret-agent/files/7511324/2021-11-10T08_42_19_194Z-debug.log)

**Comment by blakebyrnes** [comment]
Thanks for reporting. We're currently outputting an "arm64" build, but not an "arm" build. You can work around this for now by installing golang 1.14 on that machine and building with an env variable of `SA_REBUILD_MITM_SOCKET=1`. I have not tested anything on a Rasberry Pi to date, so I'm not sure if it would work or not. 

NOTE: you likely do not want to install Replay on this machine (`SA_REBUILD_MITM_SOCKET=0` during install, SA_SHOW_REPLAY=0 during runtime).
