### ISSUE TITLE
agent.goto timeout with url hash

### ISSUE THREAD

**Issue by tienne** [ulixee/secret-agent#404]
secret-agent version: 1.6.1

If the url path contains a hash, a timeout occurs.

```bash
TimeoutError: Timeout waiting for "tab.goto(https://www.fragrantica.com/designers-6/#K)"
    at Timer.waitForPromise (/Users/tienne/work/scent-letter/node_modules/commons/Timer.ts:55:21)
    at Tab.goto (/Users/tienne/work/scent-letter/node_modules/core/lib/Tab.ts:375:34)
    at CommandRecorder.runCommandFn (/Users/tienne/work/scent-letter/node_modules/core/lib/CommandRecorder.ts:73:16)
    at ConnectionToClient.executeCommand (/Users/tienne/work/scent-letter/node_modules/core/server/ConnectionToClient.ts:324:14)
    at ConnectionToClient.handleRequest (/Users/tienne/work/scent-letter/node_modules/core/server/ConnectionToClient.ts:70:14)
------REMOTE CORE---------------------------------
    at Function.reviver (/Users/tienne/work/scent-letter/node_modules/commons/TypeSerializer.ts:208:26)
    at JSON.parse (<anonymous>)
    at Function.parse (/Users/tienne/work/scent-letter/node_modules/commons/TypeSerializer.ts:24:17)
    at WebSocket.<anonymous> (/Users/tienne/work/scent-letter/node_modules/client/connections/RemoteConnectionToCore.ts:67:42)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (/Users/tienne/work/scent-letter/node_modules/ws/lib/websocket.js:983:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.dataMessage (/Users/tienne/work/scent-letter/node_modules/ws/lib/receiver.js:517:14)
    at /Users/tienne/work/scent-letter/node_modules/ws/lib/receiver.js:468:23
    at /Users/tienne/work/scent-letter/node_modules/ws/lib/permessage-deflate.js:308:9
------CONNECTION----------------------------------
    at new Resolvable (/Users/tienne/work/scent-letter/node_modules/commons/Resolvable.ts:17:18)
    at Object.createPromise (/Users/tienne/work/scent-letter/node_modules/commons/utils.ts:68:10)
    at RemoteConnectionToCore.createPendingResult (/Users/tienne/work/scent-letter/node_modules/client/connections/ConnectionToCore.ts:357:31)
    at RemoteConnectionToCore.internalSendRequestAndWait (/Users/tienne/work/scent-letter/node_modules/client/connections/ConnectionToCore.ts:263:43)
    at RemoteConnectionToCore.sendRequest (/Users/tienne/work/scent-letter/node_modules/client/connections/ConnectionToCore.ts:164:17)
    at Object.cb (/Users/tienne/work/scent-letter/node_modules/client/lib/CoreCommandQueue.ts:104:26)
    at Queue.next (/Users/tienne/work/scent-letter/node_modules/commons/Queue.ts:82:19)
------CORE COMMANDS-------------------------------
    at Queue.run (/Users/tienne/work/scent-letter/node_modules/commons/Queue.ts:35:19)
    at CoreCommandQueue.run (/Users/tienne/work/scent-letter/node_modules/client/lib/CoreCommandQueue.ts:100:8)
    at CoreTab.goto (/Users/tienne/work/scent-letter/node_modules/client/lib/CoreTab.ts:95:36)
    at Tab.goto (/Users/tienne/work/scent-letter/node_modules/client/lib/Tab.ts:160:36)
```

**Comment by tienne** [comment]
When will this be released?

**Comment by blakebyrnes** [comment]
Will put out a new release tomorrow
