### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dpirvoiu** [ulixee/secret-agent#410]
command : `yarn add secret-agent`
output : 
```
Exit code: 1
Command: node install.js
Arguments:
Directory: D:\Temp_projects\e2\node_modules\@secret-agent\chrome-88-0
Output:
D:\Temp_projects\e2\node_modules\@secret-agent\chrome-app\index.js:31
        this.osPlatformName = options?.osPlatformName ?? ChromeApp.getOsPlatformName();
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1043:16)
    at Module._compile (internal/modules/cjs/loader.js:1091:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (D:\Temp_projects\e2\node_modules\@secret-agent\chrome-88-0\index.js:2:19)
```
OS : WIN 10
node : v13.2.0
npm : 6.13.1

**Comment by blakebyrnes** [comment]
Can you use node 14? I think this bug is that optional chaining was not introduced as a default until 14.

**Comment by dpirvoiu** [comment]
Thank you @blakebyrnes , node v14 solved the problem !
