### ISSUE TITLE
aws lambda support?

### ISSUE THREAD

**Issue by johnHastings772** [ulixee/secret-agent#434]
I guess it's unsupported right now but... would it be possible to run secret-agent on aws lambda with or without any limitations?

I'm trying to get it running but I keep getting PipeTransport errors on the real aws enviroment while on a local invocation works just fine.

This is an excerpt of the log:

`2022-01-28T11:42:40.802Z ERROR [/var/task/node_modules/@secret-agent/puppet/lib/PipeTransport] PipeTransport.WriteError { context: {}, sessionId: [1mnull[22m, sessionName: [90mundefined[39m } Error: read ECONNRESET

[90m    at Pipe.onStreamRead (internal/stream_base_commons.js:209:20)[39m {

errno: [33m-104[39m,

code: [32m'ECONNRESET'[39m,

syscall: [32m'read'[39m

}

2022-01-28T11:42:40.803Z ERROR [/var/task/node_modules/@secret-agent/puppet/lib/PipeTransport] PipeTransport.WriteError { context: {}, sessionId: [1mnull[22m, sessionName: [90mundefined[39m } Error: read ECONNRESET

[90m    at Pipe.onStreamRead (internal/stream_base_commons.js:209:20)[39m {

errno: [33m-104[39m,

code: [32m'ECONNRESET'[39m,

syscall: [32m'read'[39m

}

2022-01-28T11:42:40.804Z INFO [/var/task/node_modules/@secret-agent/puppet/lib/PipeTransport] PipeTransport.Closed { context: {} }

2022-01-28T11:42:40.820Z STATS [/var/task/node_modules/@secret-agent/puppet/lib/BrowserProcess] chrome.ProcessExited { context: {} }

2022-01-28T11:42:40.821Z INFO [/var/task/node_modules/@secret-agent/core/lib/Session] Session.Closing { context: {} }`

Looking at the stacktrace it seems that there's some problem while launching chrome and thus the connection is closed.

**Comment by johnHastings772** [comment]
Hi! I tried with latest chomemium 88 binary from https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux/ and as before it works just fine on local but on lambda I got an error, a different one this time:

On the lambda call where the exception error is logged:
{
  "message": "CoreServer needs further setup to launch the browserEmulator. See server logs.",
  "name": "Error",
  "stack": "Error: CoreServer needs further setup to launch the browserEmulator. See server logs.\n    at ConnectionToClient.serializeError (/var/task/node_modules/core/server/ConnectionToClient.ts:372:14)\n    at ConnectionToClient.handleRequest (/var/task/node_modules/core/server/ConnectionToClient.ts:94:19)\n------REMOTE CORE---------------------------------\n    at Function.reviver (/var/task/node_modules/commons/TypeSerializer.ts:208:26)\n    at JSON.parse (<anonymous>)\n    at Function.parse (/var/task/node_modules/commons/TypeSerializer.ts:24:17)\n    at WebSocket.<anonymous> (/var/task/node_modules/client/connections/RemoteConnectionToCore.ts:67:42)\n    at WebSocket.emit (events.js:400:28)\n    at WebSocket.emit (domain.js:475:12)\n    at Receiver.receiverOnMessage (/var/task/node_modules/ws/lib/websocket.js:1008:20)\n    at Receiver.emit (events.js:400:28)\n    at Receiver.emit (domain.js:475:12)\n    at Receiver.dataMessage (/var/task/node_modules/ws/lib/receiver.js:517:14)\n------CONNECTION----------------------------------\n    at new Resolvable (/var/task/node_modules/commons/Resolvable.ts:16:18)\n    at Object.createPromise (/var/task/node_modules/commons/utils.ts:68:10)\n    at RemoteConnectionToCore.createPendingResult (/var/task/node_modules/client/connections/ConnectionToCore.ts:357:31)\n    at RemoteConnectionToCore.internalSendRequestAndWait (/var/task/node_modules/client/connections/ConnectionToCore.ts:263:43)\n    at RemoteConnectionToCore.sendRequest (/var/task/node_modules/client/connections/ConnectionToCore.ts:164:17)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at CoreCommandQueue.sendRequest (/var/task/node_modules/client/lib/CoreCommandQueue.ts:150:22)\n    at Object.cb (/var/task/node_modules/client/lib/CoreCommandQueue.ts:117:16)\n    at Queue.next (/var/task/node_modules/commons/Queue.ts:82:19)\n------CORE COMMANDS-------------------------------\n    at Queue.run (/var/task/node_modules/commons/Queue.ts:35:19)\n    at CoreCommandQueue.run (/var/task/node_modules/client/lib/CoreCommandQueue.ts:114:8)\n    at RemoteConnectionToCore.createSession (/var/task/node_modules/client/connections/ConnectionToCore.ts:205:51)\n    at SessionConnection.getCoreSessionOrReject (/var/task/node_modules/client/lib/Agent.ts:559:36)\n    at SessionConnection.get activeTab [as activeTab] (/var/task/node_modules/client/lib/Agent.ts:480:10)\n    at Agent.get activeTab [as activeTab] (/var/task/node_modules/client/lib/Agent.ts:152:37)\n    at Agent.goto (/var/task/node_modules/client/lib/Agent.ts:365:17)\n    at Runtime.exports.handler (/var/task/app.js:41:42)\n    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
}

On the cloundfront log
`2022-01-31T08:46:02.986Z STATS [/var/task/node_modules/@secret-agent/puppet/index] Puppet.LaunchError { context: {} } [PuppetLaunchError: EROFS: read-only file system, open '/opt/chrome/.validated'
Error: EROFS: read-only file system, open '/opt/chrome/.validated'] {
isSandboxError: false
}
2022-01-31T08:46:02.987Z ERROR [/var/task/node_modules/@secret-agent/core/server/ConnectionToClient] ConnectionToClient.HandleRequestError { context: {}, sessionId: undefined, sessionName: undefined } [PuppetLaunchError: EROFS: read-only file system, open '/opt/chrome/.validated'
Error: EROFS: read-only file system, open '/opt/chrome/.validated'] {
isSandboxError: false`

This two flags are being used to launch chrome:

'--homedir=/tmp',
'--user-data-dir=/tmp/chrome-user-data',

I have no idea where that .validated dir comes from, is it something custom from the browser emulator?

**Comment by blakebyrnes** [comment]
Thanks for running these experiments! It's been awhile since I've used Lambda. You used to have to pre-compile native modules and package them. Is that still true?

You're correct - the .validated folder is whether we've checked linux dependencies. On debian based Operating systems, we have a .deb file that will install any missing deps so that Chrome has everything it needs. I'm not sure if the binaries you're finding are coming with everything or not.

This is an example of one of the projects I'd seen in the past that precompiled some binaries: https://github.com/alixaxel/chrome-aws-lambda/tree/master/bin

Regarding Core->Client, SecretAgent is forking a process and then (if you are using the default full-client project), it communicates over a socket to that process. I'm not sure what restrictions Lambda puts on launching processes. I'm guessing there are probably some other logs that are happening that show something else breaking prior to this?

**Comment by johnHastings772** [comment]
Well for deploying to aws I'm using docker images which you can build taking base on other images, there's  one with node14 provided by amazon, so it's just a matter of installing any node modules with npm install and the required dependencies of those modules (in this case not only the modules but the chrome binary too) on the base system ex: gtk, alsa, etc....

Using the binary from chrome-aws-lambda I think I have it working but with a lot of kludges, still need to do more testing code/cleanup.
